// Code generated by MockGen. DO NOT EDIT.
// Source: ../../service/admin.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	model "github.com/LGROW101/assessment-tax/model"
	gomock "github.com/golang/mock/gomock"
)

// MockAdminServiceInterface is a mock of AdminServiceInterface interface.
type MockAdminServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAdminServiceInterfaceMockRecorder
}

// MockAdminServiceInterfaceMockRecorder is the mock recorder for MockAdminServiceInterface.
type MockAdminServiceInterfaceMockRecorder struct {
	mock *MockAdminServiceInterface
}

// NewMockAdminServiceInterface creates a new mock instance.
func NewMockAdminServiceInterface(ctrl *gomock.Controller) *MockAdminServiceInterface {
	mock := &MockAdminServiceInterface{ctrl: ctrl}
	mock.recorder = &MockAdminServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdminServiceInterface) EXPECT() *MockAdminServiceInterfaceMockRecorder {
	return m.recorder
}

// GetConfig mocks base method.
func (m *MockAdminServiceInterface) GetConfig() (*model.AdminConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfig")
	ret0, _ := ret[0].(*model.AdminConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfig indicates an expected call of GetConfig.
func (mr *MockAdminServiceInterfaceMockRecorder) GetConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfig", reflect.TypeOf((*MockAdminServiceInterface)(nil).GetConfig))
}

// UpdateConfig mocks base method.
func (m *MockAdminServiceInterface) UpdateConfig(config *model.AdminConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateConfig", config)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateConfig indicates an expected call of UpdateConfig.
func (mr *MockAdminServiceInterfaceMockRecorder) UpdateConfig(config interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateConfig", reflect.TypeOf((*MockAdminServiceInterface)(nil).UpdateConfig), config)
}
