name: CI and CD
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  PROJECT_NAME: basic-Kubernetes
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.1
      - name: Build
        run: go build -v ./...
        working-directory: assessment-tax
      - name: Test
        run: |
          go test -v ./... -coverprofile=coverage.out
          go tool cover -func=coverage.out
        working-directory: assessment-tax
      - name: Upload coverage file
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: assessment-tax/coverage.out

  build-and-push-docker-image:
    name: Build Image and Push to Registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup SHA
        run: echo "GITHUB_SHA=${GITHUB_SHA}" >> $GITHUB_ENV
      - name: Login ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GIT_TOKEN }}
      - name: Prepare repository name
        run: echo "REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      - name: Build and push API Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./assessment-tax
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ghcr.io/${{ env.REPO_NAME }}/assessment-tax-api:${{ env.GITHUB_SHA }}
      - name: Build and push Client Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./client
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ghcr.io/${{ env.REPO_NAME }}/assessment-tax-client:${{ env.GITHUB_SHA }}

  gitops-dev-versioning:
    runs-on: ubuntu-latest
    needs: build-and-push-docker-image
    name: GitOps Dev Versioning
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Config git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
      - name: Prepare repository name
        run: echo "REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      - name: Update image tags
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          sed -i "s|image: .*assessment-tax-api.*|image: ghcr.io/${{ env.REPO_NAME }}/assessment-tax-api:${{ env.GITHUB_SHA }}|" k8s/backend/api-deployment.yml
          sed -i "s|image: .*assessment-tax-client.*|image: ghcr.io/${{ env.REPO_NAME }}/assessment-tax-client:${{ env.GITHUB_SHA }}|" k8s/frontend/client-deployment.yml
          git add k8s/backend/api-deployment.yml k8s/frontend/client-deployment.yml
          git commit -m "[skip actions] 🤖 Update dev docker image version to ${GITHUB_SHA}"
          git pull --rebase
          git push
